services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: